"use client";
import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import { DM_Sans } from "next/font/google";
import "./globals.scss";
import FooterLayout from "./footer/FooterLayout";
import NavbarLayout from "./navbar/components/NavbarLayout";
import { usePathname } from "next/navigation";
import { Toaster } from "@/components/ui/toaster"


const dmsans = DM_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isBlogOrProjectPage =
    pathname.startsWith("/blogs/") || pathname.startsWith("/projects/");
  return (
    <html lang="en" className={`${isBlogOrProjectPage ? 'scroll-pt-[4.5rem]' : ''}`} style={{scrollBehavior:'smooth'}}>
      <body className={`${dmsans.className} bg-[#FCF1D8]`}>
        {children}
        <Toaster />
        <FooterLayout></FooterLayout>
      </body>
    </html>
  );
}
